/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static Controller.ControllerSalaried.consultEqualSignSalariedCtr;
import static Controller.ControllerSalaried.salariedReturnObjectWithSignCtr;
import static Controller.ControllerSalaried.updateDateCtr;
import static Controller.ControllerVehicle.countVehicleCtr;
import static Controller.ControllerVehicle.editVehicleCtr;
import static Controller.ControllerVehicle.insertVehicleCtr;
import static Controller.ControllerVehicle.returnAllVehiclesCtr;
import static Controller.ControllerVehicle.updateSalariedExitDateCtr;
import static Controller.ControllerVehicle.vehicleReturnWithCodeObjectCtr;
import static Controller.ControllerVehicle.verifyVehicleExitEntraceCtr;
import static database.VehicleSQL.updateVehicleExit;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import model.Parking;
import model.Salaried;
import model.Vehicle;
import utilitarios.LtpUtil;
import utilitarios.LtpUtilException;
import static view.SalariedRegister.returnObject;

/**
 *
 * @author rodrigo.martins
 */
public class EntraceVehicle extends javax.swing.JFrame {

    Parking park = view.ParkingRegister.returnObject();
    static Vehicle car = null;
    static Salaried sal = returnObject();

    public EntraceVehicle() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        showAllVehicle();
        slotsColors();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        URL url = this.getClass().getResource("/images/Parking-32.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneVehicle = new javax.swing.JScrollPane();
        jTableCar = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextSign = new javax.swing.JTextField();
        jButtonExit = new javax.swing.JButton();
        jButtonEntrace = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        slots = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrada e Saída de Veiculos");

        jTableCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket", "Cod Estacionamento", "Cod Mensalista", "Placa", "Entrada", "Saída", "Tempo", "Preço", "Valor Pago"
            }
        ));
        jTableCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarMouseClicked(evt);
            }
        });
        jScrollPaneVehicle.setViewportView(jTableCar);

        jLabel1.setText("Informe a placa do veiculo:");

        jButtonExit.setText("Saída");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonEntrace.setText("Entrada");
        jButtonEntrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntraceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextSign, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButtonEntrace, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit)
                    .addComponent(jLabel1)
                    .addComponent(jButtonEntrace)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Car-24.png"))); // NOI18N
        jLabel2.setText("Vagas disponiveis:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ok-24.png"))); // NOI18N
        jLabel3.setText("Estacionamento aberto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slots, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(slots, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/park9 (1).png"))); // NOI18N
        jLabel4.setText("Entrada e Saída de Veiculos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneVehicle, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarMouseClicked

        int row = jTableCar.getSelectedRow();

        String codeStr = (String) jTableCar.getValueAt(row, 0);
        int code = (Integer) Integer.parseInt((String) jTableCar.getValueAt(row, 0));

        car = vehicleReturnWithCodeObjectCtr(code);
    }//GEN-LAST:event_jTableCarMouseClicked

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed

        if (Utils.Generic.verifyObject(car)) {
            String sign = jTextSign.getText();
            //if (!vehicleExitCtr(sign)) {

            Timestamp dateExit = new Timestamp(System.currentTimeMillis());

            try {
                if (consultEqualSignSalariedCtr(sign)) {

                    updateDateCtr(dateExit, sign);

                    updateSalariedExitDateCtr(car.getCodigo(), dateExit);

                    updateVehicleExit(car);
                    showAllVehicle();
                } else {
                    editVehicleCtr(car);
                    showAllVehicle();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            //} else {
            //JOptionPane.showMessageDialog(this, "Este veiculo ja saiu!");
            //}
        }

    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonEntraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntraceActionPerformed

        if (verifySlots() && verifyFieldSign()) {

            String sign = jTextSign.getText();
            sal = salariedReturnObjectWithSignCtr(sign);

            if (verifyVehicleExitEntraceCtr(sign,park.getCod())) {
                if (sal != null) {

                    Timestamp dataEntrace = new Timestamp(System.currentTimeMillis());
                    Timestamp dataExit = new Timestamp(System.currentTimeMillis());

                    car = new Vehicle(0, park.getCod(), sal.getCodigo(), sign, dataExit, dataExit, 0, park.getTarifa_por_hora(), 0);

                    insertVehicleCtr(car);
                    showAllVehicle();
                    slotsColors();

                } else {

                    Timestamp dataEntrace = new Timestamp(System.currentTimeMillis());
                    Timestamp dataExit = new Timestamp(System.currentTimeMillis());

                    car = new Vehicle(0, park.getCod(), 0, sign, dataExit, dataExit, 0, park.getTarifa_por_hora(), 0);

                    insertVehicleCtr(car);
                    showAllVehicle();
                    slotsColors();

                }
            } else {
                JOptionPane.showMessageDialog(this, "Este veiculo ainda não saiu para dar outra entrada!");
            }
        }
    }//GEN-LAST:event_jButtonEntraceActionPerformed

    private boolean verifySlots() {

        int count = countVehicleCtr();
        int countSlots = park.getNum_vagas();
        int result = countSlots - count;
        if (count >= countSlots) {
            JOptionPane.showMessageDialog(this, "Estacionamento lotado!");
            return false;
        }
        return true;
    }

    private void slotsColors() {
        int count = countVehicleCtr();
        int countSlots = park.getNum_vagas();
        int result = countSlots - count;
        if (result <= 5) {
            slots.setForeground(Color.red);
            slots.setText(String.valueOf(result));
        } else {
            if (result <= 15) {
                slots.setForeground(Color.BLUE);
                slots.setText(String.valueOf(result));
            } else {
                slots.setForeground(Color.GREEN);
                slots.setText(String.valueOf(result));

            }
        }
    }

    private void showAllVehicle() {
        try {
            ResultSet resp = (ResultSet) returnAllVehiclesCtr(park.getCod());
            LtpUtil.loadFormatJTable(jScrollPaneVehicle, resp);
        } catch (SQLException | LtpUtilException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public boolean verifyFieldSign() {

        if (jTextSign.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor informar a placa do veiculo, antes de dar a entrada!");
            return false;
        }
        return true;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntraceVehicle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntraceVehicle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntraceVehicle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntraceVehicle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntraceVehicle().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrace;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPaneVehicle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCar;
    private javax.swing.JTextField jTextSign;
    private javax.swing.JLabel slots;
    // End of variables declaration//GEN-END:variables
}
